'use strict';
// Theme prompts drawn each round. Deliberately absurd — funnier songs, less blank-page panic.
module.exports = [
  'the final boss of a laundromat',
  'a love song for a vending machine',
  'walking into the wrong meeting',
  'a goose that owes you money',
  'the elevator to floor 47',
  'sunrise, but menacing',
  'your fridge at 3am',
  'a car chase in a shopping trolley',
  'the sad clown wins the lottery',
  'aliens discover instant noodles',
  'the last two minutes of a heist',
  'a duck with a briefcase',
  'medieval tax collection',
  'losing your keys, dramatically',
  'a haunted bouncy castle',
  'the microwave finishes at last',
  'a robot learning to flirt',
  'the office plant is judging you',
  'skateboarding down a volcano',
  'a very polite thunderstorm',
  'the worst pirate on the crew',
  'waiting for a bus that never comes',
  'a wizard doing paperwork',
  'the cat has plans',
  'underwater disco',
  'running from a bee',
  'the vending machine ate your coin',
  'a spy who is extremely bad at it',
  'first day at the cursed factory',
  'a snail in a hurry',
  'the moon is slightly closer today',
  'grandma enters the boxing ring',
  'a printer gaining sentience',
  'the swamp is throwing a party',
  'someone stole the sun',
  'a very serious duck race',
  'trapped inside a jukebox',
  'the ice cream truck is following you',
  'a dragon with a head cold',
  'closing time at the space station',
  'the toaster remembers everything',
  'a heroic nap',
  'stampede of tiny horses',
  'the librarian has had enough',
  'sneaking snacks at 2am',
  'a ghost that only haunts Tuesdays',
  'the escalator goes down forever',
  'a detective who solves nothing',
  'the last slice of pizza',
  'clouds unionise',
  'a frog running for mayor',
  'lost in a very large supermarket',
  'the volcano needs a holiday',
  'a sword that complains a lot',
  'raccoon breaks into the bank',
  'the WiFi is down and so are we',
  'a countdown that never ends',
  'the disco ball falls',
  'a train that only goes uphill',
  'everything is fine (it is not)',
];
